'use client';

import { Loader2 } from 'lucide-react';
import { PageContainer } from '@/components/page-container';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import type { Doc } from '@/convex/_generated/dataModel';
import { useActionCards } from '@/hooks/use-action-cards';
import { ActionInboxCard } from './action-card';

export function ActionInboxClient() {
  const {
    cards,
    isLoading,
    selectedIndex,
    setSelectedIndex,
    acceptSelected,
    rejectSelected,
    pendingActionId,
  } = useActionCards();

  const hasCards = cards.length > 0;

  return (
    <PageContainer className="py-8 space-y-6">
      <div className="space-y-2">
        <h1 className="text-2xl font-semibold tracking-tight">Action Inbox</h1>
        <p className="text-sm text-muted-foreground">
          Quality-control proposals generated by IQC. Review merges and keep your concepts clean.
        </p>
      </div>

      {isLoading ? (
        <Card className="flex min-h-[200px] items-center justify-center border-dashed">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
            Loading action cards…
          </div>
        </Card>
      ) : hasCards ? (
        <div className="space-y-4">
          {cards.map((card: Doc<'actionCards'>, index: number) => (
            <ActionInboxCard
              key={card._id}
              card={card}
              isSelected={selectedIndex === index}
              pending={pendingActionId === card._id}
              onAccept={() => {
                setSelectedIndex(index);
                acceptSelected();
              }}
              onReject={() => {
                setSelectedIndex(index);
                rejectSelected();
              }}
            />
          ))}
        </div>
      ) : (
        <Card className="p-8 text-center text-sm text-muted-foreground border-dashed">
          Inbox is clear. New proposals will appear after IQC scans complete.
        </Card>
      )}

      {hasCards ? (
        <div className="flex items-center gap-2">
          <Button onClick={acceptSelected} disabled={pendingActionId !== null}>
            Accept (Enter)
          </Button>
          <Button variant="outline" onClick={rejectSelected} disabled={pendingActionId !== null}>
            Reject
          </Button>
          <p className="text-xs text-muted-foreground">
            Use J / K to navigate cards, Enter to accept.
          </p>
        </div>
      ) : null}
    </PageContainer>
  );
}
