name: Convex Schema Reminder

on:
  pull_request:
    paths:
      - 'convex/**'

jobs:
  remind:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment reminder
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            📦 **Convex Schema Changed**

            Remember to deploy to production before merging:
            ```bash
            pnpm convex:deploy:prod
            ```