name: Dependency Review

on:
  pull_request:
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'package-lock.json'
      - 'yarn.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on critical or high severity vulnerabilities
          fail-on-severity: high
          # Warn about moderate vulnerabilities
          warn-on-severity: moderate
          # Check both runtime and development dependencies
          scope: runtime, development
          # Deny problematic licenses (removed allow-licenses to fix conflict)
          deny-licenses: GPL-3.0, AGPL-3.0, LGPL-3.0, MPL-2.0
          # Comment on PR with results
          comment-summary-in-pr: always
          # Show OpenSSF Scorecard for dependencies
          show-openssf-scorecard: true